# Generated by Django 5.0.4 on 2024-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appjesusgarcia", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="estudiante",
            name="apellidos",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="fecha_nacimiento",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="nombre",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
