# Generated by Django 5.0.4 on 2024-06-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appjesusgarcia", "0007_estudiante_curso_alter_curso_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="asignatura",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
