# Generated by Django 5.0.4 on 2024-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appjesusgarcia", "0008_estudiante_asignatura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="asignatura",
        ),
        migrations.AddField(
            model_name="curso",
            name="asignatura",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
